name    'fungusakafungus-github_public_keys'
version '0.0.1'
author 'fungusakafungus'
license 'Apache License, Version 2.0'
summary 'Puppet function to get users public keys from github'
project_page 'https://github.com/fungusakafungus/puppet_github_public_keys'
